name: Trigger auto deployment for ruskdesk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/ruskdesk-AutoDeployTrigger-250ed31b-ee90-41eb-a7c9-6b727b2e1746.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RUSKDESK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RUSKDESK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RUSKDESK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.RUSKDESK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RUSKDESK_REGISTRY_PASSWORD }}
          containerAppName: ruskdesk
          resourceGroup: DefaultResourceGroup-SE
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


